{
	kind: 'drive#file',
	copyRequiresWriterPermission: false,
	writersCanShare: true,
	viewedByMe: true,
	mimeType: 'application/vnd.google-apps.folder',
	parents: [ '0AKnbXuxHq_caUk9PVA' ],
	iconLink: 'https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.folder',
	shared: false,
	lastModifyingUser: {
		displayName: '000 Drive',
		kind: 'drive#user',
		me: true,
		permissionId: '07452688461755305462',
		emailAddress: 'jgprojetodrive000@gmail.com',
		photoLink: 'https://lh3.googleusercontent.com/a/default-user=s64'
	},
	owners: [
		{
			displayName: '000 Drive',
			kind: 'drive#user',
			me: true,
			permissionId: '07452688461755305462',
			emailAddress: 'jgprojetodrive000@gmail.com',
			photoLink: 'https://lh3.googleusercontent.com/a/default-user=s64'
		}
	],
	webViewLink: 'https://drive.google.com/drive/folders/1MqbJwIzuFwxpvcNbDPNRsdgqF3IoPu7g',
	viewersCanCopyContent: true,
	permissions: [
		{
			id: '07452688461755305462',
			displayName: '000 Drive',
			type: 'user',
			kind: 'drive#permission',
			photoLink: 'https://lh3.googleusercontent.com/a/default-user=s64',
			emailAddress: 'jgprojetodrive000@gmail.com',
			role: 'owner',
			deleted: false,
			pendingOwner: false
		}
	],
	hasThumbnail: false,
	spaces: [ 'drive' ],
	folderColorRgb: '#8f8f8f',
	id: '1MqbJwIzuFwxpvcNbDPNRsdgqF3IoPu7g',
	name: 'Shared 001',
	starred: false,
	trashed: true,
	explicitlyTrashed: true,
	createdTime: '2023-07-05T20:10:05.852Z',
	modifiedTime: '2023-07-05T20:11:05.231Z',
	modifiedByMeTime: '2023-07-05T20:11:05.231Z',
	viewedByMeTime: '2023-07-05T20:10:05.852Z',
	quotaBytesUsed: '0',
	version: '3',
	ownedByMe: true,
	isAppAuthorized: false,
	capabilities: {
		canChangeViewersCanCopyContent: false,
		canEdit: true,
		canCopy: false,
		canComment: true,
		canAddChildren: true,
		canDelete: true,
		canDownload: true,
		canListChildren: true,
		canRemoveChildren: true,
		canRename: true,
		canTrash: true,
		canReadRevisions: false,
		canChangeCopyRequiresWriterPermission: false,
		canMoveItemIntoTeamDrive: false,
		canUntrash: true,
		canModifyContent: true,
		canMoveItemOutOfDrive: false,
		canAddMyDriveParent: false,
		canRemoveMyDriveParent: true,
		canMoveItemWithinDrive: true,
		canShare: true,
		canMoveChildrenWithinDrive: true,
		canModifyContentRestriction: false,
		canChangeSecurityUpdateEnabled: false,
		canAcceptOwnership: false,
		canReadLabels: false,
		canModifyLabels: false
	},
	thumbnailVersion: '0',
	modifiedByMe: true,
	permissionIds: [ '07452688461755305462' ],
	linkShareMetadata: { securityUpdateEligible: false, securityUpdateEnabled: true }
}